# Generated by Django 3.2.24 on 2026-07-01 15:48

from django.db import migrations, models
import django.db.models.deletion
import reviewapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calendar_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_e', models.CharField(max_length=10)),
                ('desc_e', models.CharField(max_length=80)),
                ('type_c', models.CharField(max_length=20)),
                ('for_c', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email_hidden', models.EmailField(max_length=254)),
                ('subject_c', models.CharField(max_length=200)),
                ('against_c', models.EmailField(max_length=254)),
                ('text_c', models.CharField(max_length=500)),
                ('date_c', models.CharField(max_length=25)),
                ('to_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=8)),
                ('batch', models.CharField(max_length=10)),
                ('total_sem', models.IntegerField()),
                ('current_sem', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='inquiry_contacts_i',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=20, null=True)),
                ('admin', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='otp_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_o', models.DateTimeField(null=True)),
                ('otp_o', models.CharField(max_length=13, null=True)),
                ('user_o', models.EmailField(max_length=254)),
                ('count_o', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('start_date', models.CharField(max_length=10)),
                ('end_date', models.CharField(max_length=10)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewapp.courses')),
            ],
        ),
        migrations.CreateModel(
            name='student_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=25)),
                ('div', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('train_image', models.ImageField(null=True, upload_to=reviewapp.models.update_filename)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewapp.courses')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=50)),
                ('credit', models.IntegerField()),
                ('div_group', models.CharField(max_length=10)),
                ('count', models.CharField(default=0, max_length=2)),
                ('last_modified', models.CharField(blank=True, max_length=12, null=True)),
                ('last_modified_by', models.CharField(blank=True, max_length=20, null=True)),
                ('sem_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewapp.semester')),
            ],
        ),
        migrations.CreateModel(
            name='teacher_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('qualifications', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=7)),
                ('end_time', models.CharField(max_length=7)),
                ('room', models.IntegerField()),
                ('day', models.CharField(max_length=10)),
                ('subject_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='timetable_custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name_c', models.CharField(max_length=25)),
                ('start_time_c', models.CharField(max_length=7)),
                ('end_time_c', models.CharField(max_length=7)),
                ('room_c', models.IntegerField()),
                ('date_c', models.CharField(max_length=10)),
                ('description_c', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='timetable_deleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_c', models.CharField(max_length=10)),
                ('timetable_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewapp.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='timetable_default_custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=7)),
                ('end_time', models.CharField(max_length=7)),
                ('room', models.IntegerField()),
                ('date_c', models.CharField(max_length=10)),
                ('subject_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewapp.subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher_reference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reviewapp.teacher_data'),
        ),
        migrations.CreateModel(
            name='student_sub_elective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewapp.student_data')),
                ('subject_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviewapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='notes_d',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_n', models.FileField(upload_to='notes/')),
                ('name', models.CharField(max_length=50)),
                ('sub_n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewapp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_from', models.EmailField(max_length=254)),
                ('text_i', models.CharField(max_length=300)),
                ('time_i', models.CharField(max_length=5)),
                ('date_i', models.CharField(max_length=25)),
                ('contacts_i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewapp.inquiry_contacts_i')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_count', models.CharField(default=0, max_length=2)),
                ('marked_on', models.CharField(max_length=25, null=True)),
                ('stud_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewapp.student_data')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviewapp.subject')),
            ],
        ),
    ]
